// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
const zokratesProof = require("../../zokrates/code/square/proof.json");
    
// Test verification with incorrect proof
contract('TestIncorrectSolnSquareVerifier', accounts => {
    const owner = accounts[0];
    const account_two = accounts[1];

    describe("Verify contract with incorrect proof", function() {
        beforeEach(async function() {
            this.contract = await Verifier.new({from: owner});
        })

        it('verify with inccorect proof', async function() {
            let result = await this.contract.verifyTx.call(...Object.values(zokratesProof.proof), [32, 55], {from: owner});
        })
    })
});
